### ISSUE TITLE
Error when copying sample jupyter notebooks

### ISSUE THREAD

**Issue by llabartabajo** [burdalab/TREA#1]
Hello, I get the following error when trying to upload the .ipynb files:

Cannot upload invalid Notebook
The error was: SyntaxError: Unexpected token < in JSON at position 7

Any help is much appreciated- Looking forward to using TREA

**Comment by burdalab** [comment]
Hi, Can you tell me the steps you took to recreate the issue?

The steps needed to run jupyter notebook:

1. Download the whole repository.
2. Then run jupyter notebook from the terminal. Using the command "python -m notebook" or if you have python3 then "python3 -m notebook"
3. The above command will open Jupiter Notebook UI on your browser. Then go to the folder where downloaded repository is and open the notebook.
4. Download any missing packages using "pip install <package_name>". Only packages needed are pandas and numpy.
5. Run all the cells.

**Comment by llabartabajo** [comment]
Your answer was super helpful, it now works for me. Thanks

**Comment by burdalab** [comment]
Very glad to hear it and happy to help.
Good luck
Josh
